//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom8_IMUA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Nhom8Entities : DbContext
    {
        public Nhom8Entities()
            : base("name=Nhom8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SanPhamBanChay_Result> SanPhamBanChay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPhamBanChay_Result>("SanPhamBanChay");
        }
    }
}
